services:
  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: elvis
      POSTGRES_PASSWORD: password
      POSTGRES_DB: migrations_test
    volumes:
      - go-mg-db:/var/lib/postgresql/data

  pg_admin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "54321:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${EMAIL}
      PGADMIN_DEFAULT_PASSWORD: password
    volumes: 
      - go-mg-pgadmin:/var/lib/pgadmin

volumes:
  go-mg-db:
  go-mg-pgadmin:
